on:
  push:
    branches: [master]

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: tsufiev/test-release-action@master
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          npm-token: ${{ secrets.NODE_AUTH_TOKEN }}
          node-version: 14
          run-tests: false
