on:
  push:
    branches: [master]

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: tsufiev/test-release-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}
          node-version: 14
